version: '3'
services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
    tty: true
    stdin_open: true
    volumes:
      - .:/src/my_flask
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# docker-compose pull
# docker-compose up (when updating)
